### ISSUE TITLE
[FEAT]: Replace `localhost:8000/` text with some info

### ISSUE THREAD

**Issue by alesbe** [alesbe/mini-message-board#3]
When running the app, accessing the server root path (`localhost:8000` by default) from the browser displays `Hello world!`, It would be great to display some info. This is the line to be modified:

https://github.com/alesbe/mini-message-board/blob/973cc3600b083449723279affe7278977788bafd/server/routes/home.js#L6

Some info ideas:

- Display server endpoints (for now `/`: this same page, `/messages`: endpoint to post and get messages)
- Display where the frontend is running (port 3000 by default)
- Display link to this repository
- Anything you want!

This server endpoint it's not intended to be accessed from the browser, so no HTML should be displayed!

Be creative and add any cool ideas, happy hacking! 🙌

**Comment by meetagrawal09** [comment]
Hey @alesbe, can you please assign this issue to me 
I think displaying the actual URL where the front-end is LIVE would be great

**Comment by alesbe** [comment]
Sure! That's a nice idea, I'll assign the issue :)

**Comment by meetagrawal09** [comment]
@alesbe, can we redirect the user to "http://localhost:3000" when he/she tries to access "http://localhost:8000" ? Does that sound as a better idea ? 
This way even if they put in port 8000, we show the actual app to them at port 3000 (where our front-end is LIVE)

**Comment by alesbe** [comment]
Yeah, I think that's great! I did this project a while a go so I don't exactly remember the routes right now, but redirecting to the frontend is a nice idea.

Also, what happends if the user is not in localhost? Can we redirect him to [url]:3000? Or that would be difficult?

**Comment by meetagrawal09** [comment]
Not difficult at all 
Can just do it by changing URL in the "redirect" function used

**Comment by alesbe** [comment]
Okay, seems good! Do the PR if you want :)

**Comment by meetagrawal09** [comment]
#4 Raised the PR

**Comment by alesbe** [comment]
Thanks for the PR, this is good for now!

Happy hacktoberfest 🙌
